In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix,classification_report

In [8]:
df = pd.read_csv("LRC.data",header = None)
df.head(10)

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0  T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1  I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2  D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3  N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4  G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10
5  S   4  11   5   8   3   8   8   6   9   5   6   6   0   8   9   7
6  B   4   2   5   4   4   8   7   6   6   7   6   6   2   8   7  10
7  A   1   1   3   2   1   8   2   2   2   8   2   8   1   6   2   7
8  J   2   2   4   4   2  10   6   2   6  12   4   8   1   6   1   7
9  M  11  15  13   9   7  13   2   6   2  12   1   9   8   1   1   8

In [11]:
x = df.drop(columns = 0)
y = df[0]

In [12]:
x,y

(       1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
 0       2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
 1       5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
 2       4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
 3       7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
 4       2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10
 ...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
 19995   2   2   3   3   2   7   7   7   6   6   6   4   2   8   3   7
 19996   7  10   8   8   4   4   8   6   9  12   9  13   2   9   3   7
 19997   6   9   6   7   5   6  11   3   7  11   9   5   2  12   2   4
 19998   2   3   4   2   1   8   7   2   6  10   6   8   1   9   5   8
 19999   4   9   6   6   2   9   5   3   1   8   1   8   2   7   2   8
 
 [20000 rows x 16 columns],
 0        T
 1        I
 2        D
 3        N
 4        G
         ..
 19995    D
 19996    C
 19997    T
 19998    

In [13]:
le = LabelEncoder()
y_encode = le.fit_transform(y)
y_onehot = to_categorical(y_encode)

In [41]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y_onehot,test_size = 0.2,random_state = 123)
y_test_lable = np.argmax(ytest,axis=1)
y_test_lable 

array([19, 13, 15, ...,  8, 25,  2], dtype=int64)

In [16]:
se = StandardScaler()
xtrain = se.fit_transform(xtrain)
xtest = se.transform(xtest)

In [25]:
model = Sequential([
    Dense(64,activation = "relu",input_shape = (16,)),
    Dense(32,activation = "relu"),
    Dense(26,activation = "softmax")
])
model.compile(optimizer = "adam" ,loss = "categorical_crossentropy" , metrics = ['accuracy'])

In [26]:
model.fit(xtrain,ytrain,epochs = 11 , verbose = 1,validation_split = 0.2,batch_size = 32)

Epoch 1/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2836 - loss: 2.6337 - val_accuracy: 0.6647 - val_loss: 1.2278
Epoch 2/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7064 - loss: 1.0693 - val_accuracy: 0.7528 - val_loss: 0.8739
Epoch 3/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7906 - loss: 0.7758 - val_accuracy: 0.7925 - val_loss: 0.7119
Epoch 4/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8158 - loss: 0.6411 - val_accuracy: 0.8184 - val_loss: 0.6177
Epoch 5/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8378 - loss: 0.5580 - val_accuracy: 0.8381 - val_loss: 0.5516
Epoch 6/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.8589 - loss: 0.4816 - val_accuracy: 0.8553 - val_loss: 0.4951
Epoch 7/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8630 - loss: 0.4539 - val_accuracy: 0.8650 - val_loss: 0.4541
Epoch 8/11
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8774 - loss: 0.4145 - val_ac

In [27]:
loss,acc = model.evaluate(xtest,ytest)
loss,acc

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8790 - loss: 0.3698


(0.3705143630504608, 0.8799999952316284)

In [43]:
y_predict_prob = model.predict(xtest)
y_pred_label = np.argmax(y_predict_prob,axis = 1)
y_pred_label

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([2, 2, 2, ..., 4, 4, 2], dtype=int64)

In [44]:
cm = confusion_matrix(y_test_lable,y_pred_label)
cm

array([[  0,   0,  80,   0,   7,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  87,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 106,   0,  24,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  10,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 161,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 149,   0,  21,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 125,   0,  11,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   8,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 128,   0,  18,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 136,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  24,   0,   0,   0,   

In [50]:
print(classification_report(y_test_lable,y_pred_label))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       174
           1       0.00      0.00      0.00       140
           2       0.05      0.99      0.10       162
           3       0.00      0.00      0.00       172
           4       0.03      0.08      0.04       144
           5       0.00      0.00      0.00       149
           6       0.00      0.00      0.00       161
           7       0.00      0.00      0.00       136
           8       0.00      0.00      0.00       179
           9       0.00      0.00      0.00       144
          10       0.00      0.00      0.00       153
          11       0.00      0.00      0.00       145
          12       0.00      0.00      0.00       168
          13       0.00      0.00      0.00       149
          14       0.00      0.00      0.00       144
          15       0.00      0.00      0.00       149
          16       0.16      0.44      0.24       158
          17       0.00    

c:\Users\anime\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anime\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\anime\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo